language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: linux
      rust: stable
      env: 
        - TARGET=x86_64-unknown-linux-musl
        - PKG_CONFIG_ALLOW_CROSS=1
      dist: xenial
      addons:
        apt:
          packages: *musl_packages 
            - libssl-dev 
            - pkg-config 
            - openssl

  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

jobs:
  include:
    - stage: "Test"
      script: cargo test --verbose --all
    - stage: "Build"
      script: cargo build --verbose --all
    - stage: "releases"
      script: cargo build --verbose --all --target x86_64-unknown-linux-musl

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "target/x86_64-unknown-linux-musl/release/s3rs"
  skip_cleanup: true
  draft: true
