language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_deploy: 
  script:
    - cargo build --verbose --all --target x86_64-unknown-linux-musl --release
    - git config --local user.name "yanganto"
    - git config --local user.email "yanganto@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
    - ./build-release s3rs ${TRAVIS_TAG}-linux
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "s3rs-${TRAVIS_TAG}-linux.*"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
