language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_deploy: "./build-release s3rs ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "s3rs-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
