[package]
name = "s3rs"
version = "0.1.0"
authors = ["Antonio Yang <antonio.yang@siliconmotion.com.tw>"]

[dependencies]
interactor = "0.1.1"
toml = "0.4"
serde = "1.0.43"
serde_derive = "1.0.43"
reqwest = "0.8.5"
hyper = "0.11.25"
chrono = "0.4"
rust-crypto = "0.2"
hmac = "0.4.2"
# sha2 = "0.7.1"
sha2 = "0.6.0"
base64 = "0.6.0"
rustc-serialize = "0.3"
hmac-sha1 = "0.1.3"
url = "1.7.0"
log = "0.4"
md5 = "0.3.7"
serde_json = "1.0"
regex = "0.2"

